const AllActionTypes = {
    TOGGLE_CALENDAR_HIDDEN: 'TOGGLE_CALENDAR_HIDDEN',
    TOGGLE_GUEST_HIDDEN: 'TOGGLE_GUEST_HIDDEN',
    TOGGLE_LANGUAGE_HIDDEN: 'TOGGLE_LANGUAGE_HIDDEN',
    TOGGLE_LOCATION_HIDDEN: 'TOGGLE_LOCATION_HIDDEN',
    TOGGLE_PROFILE_HIDDEN: 'TOGGLE_PROFILE_HIDDEN'
}
export default AllActionTypes;